fos_rest:
    param_fetcher_listener: force
    view:
        view_response_listener:  true
    format_listener:
        rules:
            - { path: ^/v1, prefer_extension: true, fallback_format: json, priorities: [ json ] }
    exception:
        enabled: true
        exception_controller: 'fos_rest.exception.controller:showAction'
        codes:
            'FOS\RestBundle\Exception\InvalidParameterException': 400
            '\LogicException': 404
        messages:
            'FOS\RestBundle\Exception\InvalidParameterException': true
            '\LogicException': true