version: '3.2'

services:
  nginx:
    image: nginx:stable
    ports:
      - "81:80"
    volumes:
      - source_code:/www/tao
      - ./docker/nginx/tao.conf:/etc/nginx/conf.d/default.conf

  taoapp:
    build:
      context: ./docker/php-fpm
    volumes:
      - source_code:/www/tao
    working_dir: /www/tao

volumes:
  source_code:
    driver: local
    driver_opts:
      type: none
      device: $PWD
      o: bind



