# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration


# By updating the following the parameteres on we can load different data sources from configurable
# root resources path and filename and resource type. For our exanple changing json to csv is enough for loading
# the csv resource.
#the rest of the project remains the same.
parameters:
    app.resource_dir: '%env(REOUSRCE_SOURCE)%'
    app.resource_file_name: 'testtakers'
    app.resource_type: 'json'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            kstirkou\OAT\Repository\UserRepository $userRepository: '@kstirkou.default.user_repository'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    kstirkou\OAT\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    kstirkou\OAT\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    get_set_method_normalizer:
        class: kstirkou\OAT\Normalizer\UserCollectionNormalizer
        public: false
        tags: [serializer.normalizer]
    #User defined user repository as service.
    kstirkou.default.user_repository:
        class: kstirkou\OAT\Repository\UserRepository
        public: false
        arguments:
            $resourceDir: '%app.resource_dir%'
            $resourceFileName: '%app.resource_file_name%'
            $resourceType: '%app.resource_type%'
